[package]
name = "log_viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
rust-fuzzy-search = "0.1.1"
strip-ansi-escapes = "0.2.1"
